<a href="https://colab.research.google.com/github/Ujjwalsahu001/Google-Colab-P/blob/main/SongsAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df = pd.read_csv("/content/songs.csv", encoding='latin1')

In [ ]:
df

,Unnamed: 0,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption
0,0,F44TK5EHCRo,T-Series,RAFTA RAFTA (Lo-Fi Mix) | Dj Moody | KK | Jeet...,"Presenting the song ""RAFTA RAFTA (Lo-Fi Mix)"" ...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T12:30:08Z,7299,241,0,59,PT4M42S,hd,False
1,1,adx8Rsjp-c0,T-Series,"TUM HO MERA PYAR (Lo-Fi Mix) | Dj Moody | KK, ...","Presenting the song ""TUM HO MERA PYAR (Lo-Fi M...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T10:30:01Z,4212,144,0,32,PT5M27S,hd,False
2,2,36nQLyrR7Sw,T-Series,ISHQ HOTHON SE (Lo-Fi Mix) (Audio) | Dj Moody ...,"Presenting the song ""ISHQ HOTHON SE (Lo-Fi Mix...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T09:30:00Z,2849,79,0,31,PT6M10S,hd,False
3,3,TKbifi5AMQo,T-Series,HUMKO PYAR HUA (Lo-Fi Mix) (Audio) | Dj Moody ...,"Presenting the song ""HUMKO PYAR HUA (Lo-Fi Mix...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T07:30:05Z,3991,116,0,36,PT5M59S,hd,False
4,4,NNA21SoGqss,T-Series,Har Har Mahadev (Lyrical Video): Sachet Tandon...,"T-Series Presents ""Har Har Mahadev (Lyrical Vi...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T05:30:06Z,101950,6230,0,434,PT3M37S,hd,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19340,19340,aouxczBof58,T-Series,ROLA PE GAYA FULL SONG| PATIALA HOUSE | AKSHA...,"Watch the song ""Rola Pe Gaya"" from the movie '...","['Rola Pe Gaya', 'Anushka Sharma', 'Patiala Ho...",2011-01-20T13:34:53Z,636734,943,0,18,PT1M31S,hd,False
19341,19341,NPhY3g0WE8c,T-Series,Patiala House-Official Trailer II,Patiala house upcoming movie official trailer,"['new songs', 'official trailer', 'Songs', 'Di...",2011-01-13T11:27:42Z,86841,1084,0,4,PT3M32S,sd,False
19342,19342,ZVYTLHLpgAw,T-Series,Kyun Mein Jagoon Song (Patiala House ) | Aksha...,"""Here's presenting the song """"Kyun Main Jagoon...","['film songs', 'songs', 'bollywood song', 'anu...",2011-01-07T09:36:16Z,364995,1865,0,30,PT1M46S,sd,False
19343,19343,hArZnPWxb4A,T-Series,Laung Da Lashkara (Patiala House) Full Song | ...,"Watch the full video song ""Laung Da Lashkara"" ...","['laungda lashkara', 'laung da lashkara', 'aks...",2011-01-03T07:10:25Z,13663672,67331,0,2483,PT2M51S,hd,False
19344,19344,7_4K0iDtOvs,T-Series,"""Patiala House"" Official Trailer 2 | Akshay Kumar",Here's presenting the official trailer from th...,"['Patiala House movie film', 'Patiaala House T...",2010-12-23T10:29:50Z,1662209,29257,0,73,PT3M10S,sd,False

In [ ]:
df.head()

,Unnamed: 0,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption
0,0,F44TK5EHCRo,T-Series,RAFTA RAFTA (Lo-Fi Mix) | Dj Moody | KK | Jeet...,"Presenting the song ""RAFTA RAFTA (Lo-Fi Mix)"" ...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T12:30:08Z,7299,241,0,59,PT4M42S,hd,False
1,1,adx8Rsjp-c0,T-Series,"TUM HO MERA PYAR (Lo-Fi Mix) | Dj Moody | KK, ...","Presenting the song ""TUM HO MERA PYAR (Lo-Fi M...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T10:30:01Z,4212,144,0,32,PT5M27S,hd,False
2,2,36nQLyrR7Sw,T-Series,ISHQ HOTHON SE (Lo-Fi Mix) (Audio) | Dj Moody ...,"Presenting the song ""ISHQ HOTHON SE (Lo-Fi Mix...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T09:30:00Z,2849,79,0,31,PT6M10S,hd,False
3,3,TKbifi5AMQo,T-Series,HUMKO PYAR HUA (Lo-Fi Mix) (Audio) | Dj Moody ...,"Presenting the song ""HUMKO PYAR HUA (Lo-Fi Mix...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T07:30:05Z,3991,116,0,36,PT5M59S,hd,False
4,4,NNA21SoGqss,T-Series,Har Har Mahadev (Lyrical Video): Sachet Tandon...,"T-Series Presents ""Har Har Mahadev (Lyrical Vi...","['hindi songs 2023', 'hindi songs new', 'bolly...",2023-08-20T05:30:06Z,101950,6230,0,434,PT3M37S,hd,False

In [ ]:
df.tail()

,Unnamed: 0,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption
19340,19340,aouxczBof58,T-Series,ROLA PE GAYA FULL SONG| PATIALA HOUSE | AKSHA...,"Watch the song ""Rola Pe Gaya"" from the movie '...","['Rola Pe Gaya', 'Anushka Sharma', 'Patiala Ho...",2011-01-20T13:34:53Z,636734,943,0,18,PT1M31S,hd,False
19341,19341,NPhY3g0WE8c,T-Series,Patiala House-Official Trailer II,Patiala house upcoming movie official trailer,"['new songs', 'official trailer', 'Songs', 'Di...",2011-01-13T11:27:42Z,86841,1084,0,4,PT3M32S,sd,False
19342,19342,ZVYTLHLpgAw,T-Series,Kyun Mein Jagoon Song (Patiala House ) | Aksha...,"""Here's presenting the song """"Kyun Main Jagoon...","['film songs', 'songs', 'bollywood song', 'anu...",2011-01-07T09:36:16Z,364995,1865,0,30,PT1M46S,sd,False
19343,19343,hArZnPWxb4A,T-Series,Laung Da Lashkara (Patiala House) Full Song | ...,"Watch the full video song ""Laung Da Lashkara"" ...","['laungda lashkara', 'laung da lashkara', 'aks...",2011-01-03T07:10:25Z,13663672,67331,0,2483,PT2M51S,hd,False
19344,19344,7_4K0iDtOvs,T-Series,"""Patiala House"" Official Trailer 2 | Akshay Kumar",Here's presenting the official trailer from th...,"['Patiala House movie film', 'Patiaala House T...",2010-12-23T10:29:50Z,1662209,29257,0,73,PT3M10S,sd,False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19345 entries, 0 to 19344
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     19345 non-null  int64
 1   video_id       19345 non-null  object
 2   channelTitle   19345 non-null  object
 3   title          19345 non-null  object
 4   description    19342 non-null  object
 5   tags           19345 non-null  object
 6   publishedAt    19345 non-null  object
 7   viewCount      19345 non-null  int64
 8   likeCount      19345 non-null  int64
 9   favoriteCount  19345 non-null  int64
 10  commentCount   19345 non-null  int64
 11  duration       19345 non-null  object
 12  definition     19345 non-null  object
 13  caption        19345 non-null  bool
dtypes: bool(1), int64(5), object(8)
memory usage: 1.9+ MB

In [ ]:
df.describe()

         Unnamed: 0     viewCount     likeCount  favoriteCount   commentCount
count  19345.000000  1.934500e+04  1.934500e+04        19345.0   19345.000000
mean    9672.000000  1.193826e+07  8.718149e+04            0.0    2636.024141
std     5584.564814  5.484973e+07  3.610099e+05            0.0   12487.178242
min        0.000000  0.000000e+00  0.000000e+00            0.0       0.000000
25%     4836.000000  8.044200e+04  6.440000e+02            0.0      37.000000
50%     9672.000000  3.627810e+05  3.929000e+03            0.0     184.000000
75%    14508.000000  2.613386e+06  2.580300e+04            0.0     961.000000
max    19344.000000  1.536719e+09  1.284022e+07            0.0  420375.000000

In [ ]:
df.shape

(19345, 14)

In [ ]:
df.columns

Index(['Unnamed: 0', 'video_id', 'channelTitle', 'title', 'description',
       'tags', 'publishedAt', 'viewCount', 'likeCount', 'favoriteCount',
       'commentCount', 'duration', 'definition', 'caption'],
      dtype='object')

In [ ]:
columns = df[["title","viewCount","likeCount"]]
print(columns)

                                                   title  viewCount  likeCount
0      RAFTA RAFTA (Lo-Fi Mix) | Dj Moody | KK | Jeet...       7299        241
1      TUM HO MERA PYAR (Lo-Fi Mix) | Dj Moody | KK, ...       4212        144
2      ISHQ HOTHON SE (Lo-Fi Mix) (Audio) | Dj Moody ...       2849         79
3      HUMKO PYAR HUA (Lo-Fi Mix) (Audio) | Dj Moody ...       3991        116
4      Har Har Mahadev (Lyrical Video): Sachet Tandon...     101950       6230
...                                                  ...        ...        ...
19340  ROLA PE GAYA  FULL SONG| PATIALA HOUSE | AKSHA...     636734        943
19341                  Patiala House-Official Trailer II      86841       1084
19342  Kyun Mein Jagoon Song (Patiala House ) | Aksha...     364995       1865
19343  Laung Da Lashkara (Patiala House) Full Song | ...   13663672      67331
19344  "Patiala House" Official Trailer 2 | Akshay Kumar    1662209      29257

[19345 rows x 3 columns]

In [ ]:
highest_views = df[df["viewCount"] > 15000000]
df = pd.DataFrame()
print(highest_views)

       Unnamed: 0     video_id channelTitle  \
39             39  VAdGW7QDJiU     T-Series
48             48  ZWUgBdzgGyQ     T-Series
95             95  AQEc4BwX6dk     T-Series
112           112  4-30eu39wRM     T-Series
239           239  jyZsX8OyrmQ     T-Series
...           ...          ...          ...
19295       19295  KWCLOpaZeLc     T-Series
19298       19298  -Hb2DeHvvEg     T-Series
19299       19299  jAUSF4_ygJg     T-Series
19305       19305  ZTmF2v59CtI     T-Series
19330       19330  fbdxYoFb64g     T-Series

                                                   title  \
39     Jawan: Chaleya (Hindi) | Shah Rukh Khan | Naya...
48     YAARIYAN 2 (TEASER): Divya,Yash,Meezaan,Anaswa...
95     Jawan: Zinda Banda Song |Shah Rukh Khan |Atlee...
112    Guru Randhawa: You Talking To Me? (Official Mu...
239    Tumhe Kitna Pyaar Karte (Video) Bawaal | Varun...
...                                                  ...
19295  'Tumse Hi Tumse' (Full Song) | Anjaana Anjaani...
19298  ''Tujhe Bhula Diya" (Full Song) Anjaana Anjaan...
19299  "Tu Na Jaane Aas Paas Hai Khuda" Full HD Song ...
19305  "Sheila Ki Jawani" Full Song | Tees Maar Khan ...
19330  Abhi Kuch Dino Se Full Song | Dil Toh Baccha H...

                                             description  \
39     Witness the love with Chaleya, presenting the ...
48     Presenting a glimpse of the most awaited film ...
95     Come, join the celebration & dance to the beat...
112    Presenting the New Punjabi Song, You Talking T...
239    Presenting the song, Tumhein Kitna Pyaar Karte...
...                                                  ...
19295  Watch the song "Tumse Hi Tumse" from the Bolly...
19298  Tujhe Bhula Diya is a song which is straight f...
19299  Here is the song "Tu Na Jaane Aas Paas Hai Khu...
19305  Click to Share it on Facebook - http://bit.ly/...
19330  "Abhi Kuch Dino Se" is a marvelous romantic so...

                                                    tags  \
39     ['hindi songs 2023', 'hindi songs new', 'bolly...
48     ['hindi songs 2023', 'hindi songs new', 'bolly...
95     ['hindi songs 2023', 'hindi songs new', 'bolly...
112    ['hindi songs 2023', 'bollywood songs 2023', '...
239    ['hindi songs 2023', 'hindi songs new', 'bolly...
...                                                  ...
19295  ['Tumse Hi Tumse', 'vishal dadlani', 'vishal s...
19298  ['Tujhe Bhula Diya', 'Anjana Anjani', 'Mohit C...
19299  ['Tujhe Bhula Diya', 'Anjana Anjani', 'Rahat F...
19305  ['Sheela Ki Jawani', 'Sheila Ki Jawani Full So...
19330  ['Dil Toh Baccha Hai Ji', 'Emraan Hashmi', 'Aj...

                publishedAt  viewCount  likeCount  favoriteCount  \
39     2023-08-14T06:19:10Z   39243770     903789              0
48     2023-08-10T08:00:06Z   20575342      98367              0
95     2023-07-31T07:19:08Z   59238514    1058020              0
112    2023-07-28T05:29:08Z   30084250      85425              0
239    2023-07-10T09:30:09Z   25035722     187374              0
...                     ...        ...        ...            ...
19295  2011-03-18T11:25:57Z   15605080     139650              0
19298  2011-03-18T08:25:33Z  115730543    1257792              0
19299  2011-03-18T07:45:12Z   62212769     580600              0
19305  2011-03-07T06:24:22Z  259438917    1181356              0
19330  2011-02-05T12:41:29Z   57187065     441232              0

       commentCount duration definition  caption
39            50019   PT3M8S         hd     True
48            18558  PT2M22S         hd     True
95            79310  PT3M46S         hd     True
112           27100  PT2M59S         hd    False
239           11584  PT2M16S         hd    False
...             ...      ...        ...      ...
19295          3033  PT4M28S         hd    False
19298         22382  PT4M19S         hd    False
19299          9397   PT5M4S         hd    False
19305         27354  PT4M31S         hd    False
19330            22  PT4M11S         hd    False

[2238 rows x 14 columns]

In [ ]:
df = pd.read_csv("/content/songs.csv", encoding='latin1')
filter_vandc = df[(df["viewCount"]>1500000) & (df["likeCount"] > 15000)]
print(filter_vandc)

       Unnamed: 0     video_id channelTitle  \
24             24  XRhWn0iCW9s     T-Series
34             34  qXB5Bcj7F6M     T-Series
39             39  VAdGW7QDJiU     T-Series
44             44  djXuC5EdvyA     T-Series
47             47  posAOLFBpaM     T-Series
...           ...          ...          ...
19330       19330  fbdxYoFb64g     T-Series
19332       19332  0mfen2YtSj8     T-Series
19334       19334  zqQhbs1q4-E     T-Series
19343       19343  hArZnPWxb4A     T-Series
19344       19344  7_4K0iDtOvs     T-Series

                                                   title  \
24     MERE KANHA BHOOL NA JAANA (???? ?????? ??? ?? ...
34     Spirit Of Fighter | Hrithik Roshan | Deepika P...
39     Jawan: Chaleya (Hindi) | Shah Rukh Khan | Naya...
44     VANDE BHARATAM | Vishal Mishra, Arko | Manoj M...
47     BAARISH HAI JAANAM: Payal Dev, Stebin Ben, Har...
...                                                  ...
19330  Abhi Kuch Dino Se Full Song | Dil Toh Baccha H...
19332  Jadugari Full Song | Dil toh baccha hai Ji |Aj...
19334  "Tere Bin" Dil Toh Baccha Hai Ji Full Song (HD...
19343  Laung Da Lashkara (Patiala House) Full Song | ...
19344  "Patiala House" Official Trailer 2 | Akshay Kumar

                                             description  \
24     Presenting the song "Mere Kanha Bhool Na Jaana...
34     Salute to our glorious Nation, Vande Mataram! ...
39     Witness the love with Chaleya, presenting the ...
44     Presenting the song "VANDE BHARATAM" sung by V...
47     Presenting the new Romantic Anthem "BAARISH HA...
...                                                  ...
19330  "Abhi Kuch Dino Se" is a marvelous romantic so...
19332  Here's presenting the song "Jadugari" from the...
19334  Tere bin is a beautiful romantic song sung by ...
19343  Watch the full video song "Laung Da Lashkara" ...
19344  Here's presenting the official trailer from th...

                                                    tags  \
24     ['hindi songs 2023', 'hindi songs new', 'bolly...
34     ['hindi songs 2023', 'hindi songs new', 'bolly...
39     ['hindi songs 2023', 'hindi songs new', 'bolly...
44     ['hindi songs 2023', 'hindi songs new', 'bolly...
47     ['hindi songs 2023', 'hindi songs new', 'bolly...
...                                                  ...
19330  ['Dil Toh Baccha Hai Ji', 'Emraan Hashmi', 'Aj...
19332  ['jaadugiri', 'dil toh baccha hai ji', 'ajay d...
19334  ['Shazahn Padamsee', 'Ajay Devgan', 'Emraan Ha...
19343  ['laungda lashkara', 'laung da lashkara', 'aks...
19344  ['Patiala House movie film', 'Patiaala House T...

                publishedAt  viewCount  likeCount  favoriteCount  \
24     2023-08-17T03:29:08Z    3495929      33884              0
34     2023-08-15T07:23:08Z    3439182     198182              0
39     2023-08-14T06:19:10Z   39243770     903789              0
44     2023-08-12T05:29:12Z    6267088      61679              0
47     2023-08-11T05:29:11Z    5658322      89698              0
...                     ...        ...        ...            ...
19330  2011-02-05T12:41:29Z   57187065     441232              0
19332  2011-02-05T11:41:00Z    1527535      15036              0
19334  2011-02-03T12:41:22Z    5847268      46182              0
19343  2011-01-03T07:10:25Z   13663672      67331              0
19344  2010-12-23T10:29:50Z    1662209      29257              0

       commentCount duration definition  caption
24             6505  PT6M45S         hd    False
34             4175    PT58S         hd    False
39            50019   PT3M8S         hd     True
44             7328  PT7M46S         hd    False
47             3749  PT4M14S         hd    False
...             ...      ...        ...      ...
19330            22  PT4M11S         hd    False
19332             9  PT2M58S         hd    False
19334            12  PT3M13S         sd    False
19343          2483  PT2M51S         hd    False
19344            73  PT3M10S         sd    False

[5175 rows x 14 columns]

In [ ]:
df.isnull()

,Unnamed: 0,video_id,channelTitle,title,description,tags,publishedAt,viewCount,likeCount,favoriteCount,commentCount,duration,definition,caption
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19340,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19341,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19342,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19343,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19344,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Unnamed: 0       0
video_id         0
channelTitle     0
title            0
description      3
tags             0
publishedAt      0
viewCount        0
likeCount        0
favoriteCount    0
commentCount     0
duration         0
definition       0
caption          0
dtype: int64